### ISSUE TITLE
Updating qg-frontend-v2 test coverage

### ISSUE THREAD

**Issue by mnyon-grandkru** [QueerGlobal/qg-frontend-v2#31]
Automated tests are running in GitHub Actions! The next phase is to have a test file for every `.tsx` file in the codebase. This includes the following:

- [X] src/App.ts
- [x] src/components/homepage/Homepage.tsx
- [x] src/components/home/Home.tsx
- [x] src/components/add-resource/AddResource.tsx
- [X] src/components/about/About.tsx
- [x] src/components/logout/Logout.tsx
- [x] src/components/donate/Donate.tsx
- [x] src/components/profile/Profile.tsx
- [x] src/components/navbar/Navbar.tsx
- [x] src/components/common/button/Button.tsx
- [x] src/components/common/social-icons/SocialIcons.tsx
- [X] src/components/common/footer/Footer.tsx
- [x] src/components/common/topnav/TopNav.tsx
- [x] src/components/homepageCTA2/HomepageCTA2.tsx
- [x] src/components/homepageCTA/HomepageCTA.tsx
- [x] src/components/blog/Blog.tsx
- [x] src/components/homepageLinks/HomepageLinks.tsx
- [x] src/components/search/Search.tsx

**Comment by colinwilliams91** [comment]
Smart! I should try to adhere to this too. I will do some looking around in the pre-existing files and can try and build out some unit tests for my own `.tsx` files too if you would like :)

**Comment by mnyon-grandkru** [comment]
@colinwilliams91 I think I want to expand beyond what's currently being tested. It's good to know that the copy is presenting, and I think that tests to render correctly are good tests to have for this codebase now.  As we review and implement more React best practices, our testing will evolve, as it should.

**Comment by mnyon-grandkru** [comment]
I think we can close this for now, and come up with test standards for each ticket moving forward.
